name: test

on:
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: gulp build
        uses: actions/setup-node@v2
        with:
          node-version: '14.17.4'
      - name: install
        run: npm install
      - name: build
        run: npm run build:wp:prod
